version: "3.8"

services:
    erp_database:
        image: postgres
        container_name: erp_database
        restart: always
        ports: 
            - 5432:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=erp_schema
        volumes: 
            - pgdata:/data/postgres

    app:
        build: .
        container_name: erp_app
        ports: 
            - 3333:3333
        volumes: 
            - .:/usr/app
            - /usr/app/node_modules/bcrypt/
        links: 
            - erp_database
        depends_on:
            - erp_database

volumes: 
    pgdata:
        driver: local
            